
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

language: cpp

# os:
#   - linux
#   - osx

# sudo: require # deprecated

dist: xenial

# compiler:
#   - clang 
#   - gcc

env: 
  global:
    - SOCNETV_VERSION=2.8-dev # We use it to name packages on non-tagged commits

# explicitly define our build
# maybe add a linux/clang pair ?
jobs:
  include:
    - os: linux
      compiler: gcc
      env: FAILURES=true
    - os: osx
      compiler: clang
      env: FAILURES=true
  exclude:
    - os: osx
      compiler: gcc      
  allow_failures:
    - env: FAILURES=TRUE


before_install:
  # Add repositories etc
  - chmod +x .travis_before_install.sh
  - ./.travis_before_install.sh


install: 
  - echo "Install any required packages and dependencies";
  - chmod +x .travis_install.sh
  - ./.travis_install.sh


script:
  #  Run the build script
  -  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then chmod +x .travis_build_linux.sh ; fi
  - '[ "$TRAVIS_OS_NAME" != linux ] || ./.travis_build_linux.sh'
  -  if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then chmod +x .travis_build_macos.sh ; fi  
  - '[ "$TRAVIS_OS_NAME" != osx ] || ./.travis_build_macos.sh'

after_success:
   - ls -lsh  
    #- curl --upload-file ./Social*.AppImage https://transfer.sh/SocNetV-git.$(git rev-parse --short HEAD)-x86_64.AppImage
   - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
   - echo "Listing directory"
   - ls -lsh
   - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then bash upload.sh *SocNetV*.AppImage*; fi
   - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then bash upload.sh *SocNetV*.zip*; bash upload.sh SocNetV*.pkg*; fi

