
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/

language: cpp

env: 
  global:
    - SOCNETV_VERSION=3.0-dev # We use it to name packages on non-tagged commits
    # Change me to false, on release
    - UPLOADTOOL_ISPRERELEASE=true

# explicitly define our build
# maybe add a linux/clang pair ?
jobs:
  include:
    - os: linux
      compiler: gcc
      dist: xenial
      env: FAILURES=true
    - os: osx
      compiler: clang
      env: FAILURES=true
      osx_image: xcode12
  exclude:
    - os: osx
      compiler: gcc      
  allow_failures:
    - env: FAILURES=TRUE


before_install:
  - echo "***********************************************";
  - echo " Run script before install (to add repos etc)  ";
  - echo "***********************************************";
  - chmod +x .travis_before_install.sh
  - ./.travis_before_install.sh


install:
  - echo "***********************************************"; 
  - echo " Run script to install any dependencies...     ";
  - echo "***********************************************";
  - chmod +x .travis_install.sh
  - ./.travis_install.sh


script:
  - echo "***********************************************";
  - echo " Run script to build the app...                ";
  - echo "***********************************************";
  -  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then chmod +x .travis_build_linux.sh ; fi
  - '[ "$TRAVIS_OS_NAME" != linux ] || ./.travis_build_linux.sh'
  -  if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then chmod +x .travis_build_macos.sh ; fi  
  - '[ "$TRAVIS_OS_NAME" != osx ] || ./.travis_build_macos.sh'

after_success:
  - echo "***********************************************";
  - echo " Finished building. Download upload.sh script  ";
  - echo "***********************************************";
  - ls -lsh  
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - echo "Listing directory"
  - ls -lsh
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then bash upload.sh *SocNetV*.AppImage*; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then bash upload.sh *SocNetV*.zip*; bash upload.sh SocNetV*.pkg*; fi

